# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s="hi there sam!"
x=s.split()
print(x)

['hi', 'there', 'sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [2]:
planet = "Earth"
diameter = 12742

In [5]:
txt="The diameter of {planet} is {diameter} kilometers".format(planet="earth",diameter=12742)

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [15]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'helo']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'helo'

# Numpy

In [16]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [17]:
x= [0]*10
print(x)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [18]:
y=[5]*10
print(y)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 5. Create an array of all the even integers from 20 to 35

In [24]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
X= np.arange(0,9).reshape(3,3)
print(x)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [25]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [48]:


 A =np.random.randint(10, size =(3,2))
 print(A)

[[8 9]
 [8 3]
 [0 2]]


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [37]:
import datetime
day_delta=datetime.timedelta(days=1)

start_date=datetime.date(2023,1,1)
end_date=start_date+40*day_delta

for i in range((end_date-start_date).days):
    print(start_date+1*day_delta)

2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02
2023-01-02


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [44]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
lists= pd.DataFrame(lists)
print(lists)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
